server.address=0.0.0.0
//app.cors.allowed-origins=http://192.168.0.15:4200
app.cors.allowed-origins=http://192.168.0.61:4200

app.mail.enabled=true
app.mail.to=dornyei.r@gmail.com
app.mail.from=stablemanager26@gmail.com
app.storage.low-days=14,7,2
app.mail.reminder.days=7,2
app.mail.reminder.cron=0 5 7 * * *

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stablemanager26@gmail.com
spring.mail.password=wjfz ndkq mzfd uqjj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.mime.charset=UTF-8
